area: [41, 42, 10, 13]  # lat_min, lat_max, long_min, long_max

hydrophones_config:
  hydrophones:
    - coordinates: [41.2, 11]     # Hydrophone 1
      max_range: 50                 # [km]
    - coordinates: [41.6, 12.1]     # Hydrophone 1
      max_range: 30                 # [km]
  num_random: 0                     # Generate random hydrophones
  noise_level: 2.0                  # [dB re 1 µPa]
  max_range_range: [30, 50]         # [km]

ships_config:
  ais_ships:                        # Manual ais ships
    - coordinates: [41.1, 12.4]     # AIS Ship 1
      speed: 10                     # [kt]
      base_pressure: 150            # [dB re 1 µPa]
    - coordinates: [41.8, 10.5]     # AIS Ship 2
      speed: 10                     # [kt]
  num_random_ais_ships: 0           # Generate random ais ships

  dark_ships:                       # Manual dark ships
    - coordinates: [41.4, 11.5]     # Dark Ship 1
      speed: 15                     # kt
  num_random_dark_ships: 0          # Generate random dark ships

  speed_range: [5,20]               # [kt]
