area: [0, 1000, 0, 500]  # x_min, x_max, y_min, y_max

hydrophones:
  positions:    # Manual hydrophones
    - [0, 0]    # Hydrophone 1
    - [1000, 0] # Hydrophone 2
  num_random: 0  # Generate random hydrophones
  noise_level: 2.0

ships:
  ais_ships:    # Manual ais ships
    - position: [500, 500] # AIS Ship 1
      speed: 10
    - position: [120, 600] # AIS Ship 2
      speed: 10
  num_random_ais_ships: 0 # Generate random ais ships

  dark_ships:
    - position: [300, 100]
      speed: 15
  num_random_dark_ships: 0

  speed_range: [5,20]
