output_path: "/Users/gean/Documents/Unitn/Thesis/darkships_detection/output/01output.jsonl"

environment:
  area: [10, 12, 83.5, 85.5]  # lat_min, lat_max, long_min, long_max
  bathymetry_path: "./bathymetry/bathymetry_sample.nc"

hydrophones_config:
  # DATA FOR MANUAL HYDROPHONES GENERATION
  hydrophones:
    - coordinates: [11, 83.5]     # Hydrophone 1
      max_range: 50                 # [km]
      depth: 20                     # [m]
    - coordinates: [11.2, 84.5]         # Hydrophone 2
      max_range: 30                 # [km]
      depth: 30                     # [m]
    - coordinates: [11.5, 83.8]     # Hydrophone 3
      max_range: 30                 # [km]
      depth: 30                     # [m]

  noise_level: 2.0                  # [dB re 1 µPa]

  # DATA FOR RANDOM HYDROPHONES GENERATION
  num_random: 0                     # Generate random hydrophones
  max_range_range: [30, 50]         # [km]
  depth_range: [0, 35]              # [m]

ships_config:
  # DATA FOR MANUAL SHIPS GENERATION
  # ais_ships:                        # Manual ais ships
    # - coordinates: [11.8, 83.9]     # AIS Ship 1
    #   speed: 10                     # [kt]
    #   depth: 10                     # [m]
    #   heading: 30                   # [°]
    # - coordinates: [10.4, 82.5]       # AIS Ship 2
    #   speed: 10                     # [kt]
    #   depth: 10                     # [m]
    #   heading: 270                  # [°]

  dark_ships:                       # Manual dark ships
    - coordinates: [12, 82.6]    # Dark Ship 1
      speed: 15                     # kt
      depth: 10                     # [m]
      heading: 120                  # [°]

  # DATA FOR RANDOM SHIPS GENERATION
  num_random_ais_ships: 0           # Generate random ais ships
  num_random_dark_ships: 0          # Generate random dark ships
  speed_range: [5,20]               # [kt]
  depth_range: [0, 25]              # [m]
