output_path: "./output"
name: "sample"

environment:
  area: [10, 12, 83.5, 85.5]  # lat_min, lat_max, long_min, long_max
  bathymetry_path: "./bathymetry/bathymetry_sample.nc"
  toa_variance: [1.0e-5, 1.0e-4, 1.0e-3, 1.0e-2, 1.0e-1, 1.0]

hydrophones_config:
  # DATA FOR MANUAL HYDROPHONES GENERATION
  hydrophones:
      - coordinates: [11.0, 84.0]     # Idrofono 1
        depth: 20                     # [m]
      - coordinates: [11.03, 84.0]    # Idrofono 2
        depth: 20                     # [m]
      - coordinates: [11.03, 84.03]   # Idrofono 3
        depth: 20                     # [m]
      - coordinates: [11.0, 84.03]    # Idrofono 4
        depth: 20                     # [m]
  noise_level: 2.0                  # [dB re 1 µPa]

  # DATA FOR RANDOM HYDROPHONES GENERATION
  num_random: 0                     # Generate random hydrophones
  max_range_range: [30, 50]         # [km]
  depth_range: [0, 35]              # [m]

ships_config:
  # DATA FOR MANUAL SHIPS GENERATION
  # ais_ships:                        # Manual ais ships
    # - coordinates: [11.8, 83.9]     # AIS Ship 1
    #   speed: 10                     # [kt]
    #   depth: 10                     # [m]
    #   heading: 30                   # [°]
    # - coordinates: [10.4, 82.5]       # AIS Ship 2
    #   speed: 10                     # [kt]
    #   depth: 10                     # [m]
    #   heading: 270                  # [°]

  dark_ships:                       # Manual dark ships
    - coordinates: [11.032, 84.015]    # Dark Ship 1
      speed: 10                     # kt
      depth: 20                     # [m]
      heading: 180 # [°]

  # DATA FOR RANDOM SHIPS GENERATION
  num_random_ais_ships: 0           # Generate random ais ships
  num_random_dark_ships: 0          # Generate random dark ships
  speed_range: [5,20]               # [kt]
  depth_range: [0, 25]              # [m]
