area: [0, 1000, 0, 500]  # x_min, x_max, y_min, y_max

hydrophones:
  positions:    # Manual hydrophones
    - [0, 0]    # Hydrophone 1
    - [1000, 0] # Hydrophone 2
  num_random: 3  # Generate 3 random hydrophones
  noise_level: 2.0

ships:
  ais_ships:
    - x: 500
      y: 500
      speed: 10
    - x: 340
      y: 600
      speed: 10
  dark_ships:
    - x: 100
      y: 200
      speed: 15
  num_random_ais_ships: 3
  num_random_dark_ships: 1
