environment:
  area: [10, 12, 83.5, 85.5]  # lat_min, lat_max, long_min, long_max
  bathymetry_path: "./bathymetry/bathymetry_sample.nc"

hydrophones_config:
  # DATA FOR MANUAL HYDROPHONES GENERATION
  hydrophones:
    - coordinates: [11.0, 83.5]      # Hydrophone 1 (lat: 11.0, lon: 83.5)
      max_range: 50                 # [km]
      depth: 20                     # [m]
    - coordinates: [11.15, 83.65]     # Hydrophone 2 (lat: 14.0, lon: 94.0)
      max_range: 30                 # [km]
      depth: 30                     # [m]
    - coordinates: [11.3, 83.8]     # Hydrophone 2 (lat: 14.0, lon: 94.0)
      max_range: 30                 # [km]
      depth: 30                     # [m]

  noise_level: 2.0                  # [dB re 1 µPa]

  # DATA FOR RANDOM HYDROPHONES GENERATION
  num_random: 0                     # Generate random hydrophones
  max_range_range: [30, 50]         # [km]
  depth_range: [0, 35]              # [m]

ships_config:
  # DATA FOR MANUAL SHIPS GENERATION
  ais_ships:                        # Manual ais ships
    # - coordinates: [11.8, 83.9]     # AIS Ship 1 (lat: 11.5, lon: 83.8)
    #   speed: 10                     # [kt]
    #   depth: 10                     # [m]
    - coordinates: [11.1, 84]     # AIS Ship 2 (lat: 14.5, lon: 94.0)
      speed: 10                     # [kt]
      depth: 10                     # [m]

  dark_ships:                       # Manual dark ships
    - coordinates: [11.11, 83.6]     # Dark Ship 1 (lat: 12.0, lon: 84.5)
      speed: 15                     # kt
      depth: 10                     # [m]

  # DATA FOR RANDOM SHIPS GENERATION
  num_random_ais_ships: 0           # Generate random ais ships
  num_random_dark_ships: 0          # Generate random dark ships
  speed_range: [5,20]               # [kt]
  depth_range: [0, 25]              # [m]
