area: [0, 1000, 0, 500]

hydrophones:
  positions:
    - [300, 300]
    - [350, 800]
    - [600, 575]
  num_random: 0
  noise_level: 2.0

ships:
  num_random_ais_ships: 5

  dark_ships:
    - position: [500, 500]
      speed: 15
  num_random_dark_ships: 0

  speed_range: [5,20]
